language: node_js
node_js:
  - 8.9.4
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: testtrav
  acl: public_read
  local_dir: dist
  skip_cleanup: true
