language: python
python:
    - "2.7"
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket:  testtrav
    skip_cleanup: true
    local-dir: public
    acl: public_read
    detect_encoding: true
