git:
  depth: 3
install:
- sudo apt install awscli
script: echo 'test'
sudo: required
env:
  matrix:
    secure: emzZYfRRoMZOxCem9sjtmRpGKCjZnrWu25KrSbf9WucPhRdFmwtNZ1malFHZsH32OeAr/iLzzOv8hvDUKtoadvksVRk/WVBkH6YPm2QIrmpwo2miYGqyFsQiAuwVln3vPLq50Odx0nvt1BR+9XboyykCGrI8pPe66di7KbsX7F3xS/2Y7sPX7Q0rHOeVP3B54iqqjV47Jku+B3c2ijTqEulA+1mEAnd9llgOsAMmjwFDcrIAv6pxyPudDcJCp3TAelGdRggoAx9KaoZlmQjg0xOllE/Dd+383xO8tLXL/KAHnPeA//Ar6Mmh7GkTcg/DLZ7oBx3hPn9TkBxOTkD87X5GPP+kXY9edVSGdTgFDJv+o+3QiZoEcuZam2xBehfiR6Kq/b1sY4iIKSjTTpMcX49L37TMmEunOIVE4E/1vGOXIfFASlIMQVZmrbTFgkwHvNtlFc731GKqZkL49tKAOhJp5Z4OrOLXsZvkmpDN6v8l6+5NO3lYL8ZMKxo6DI8DdXGQ6rIGPRsJFeSZVxwerZyYssqeK7Agfz+QjM4LiEu5tS6NxXxVOh5MbemYA+zw7rzuir+el7bt1bDqYEjrSXVy2axBEa/Ws7r70FO970FnlQyIwlheiRd7SDxb0CSIYMNcsRc8rKh0IuIk0aWLd2KbEAZi5VeffeWY73BFs00=
